### PR TITLE
Add COREV branching immediate instructions, and GCC tests.

### PR DESCRIPTION
**Pull request by EnricoTabanelli**
Files changed:

	*gcc/common/config/riscv/riscv-common.cc: Add "xcorev" and "xcorevbi" in riscv_implied_info_t and riscv_ext_flag_tablev.
	*gcc/config/riscv/corev.md: Add COREV machine description.
	*gcc/config/riscv/predicates.md: Add branch_simm5_operand predicate.
	*gcc/config/riscv/riscv.cc: Modify riscv_emit_int_compare() function to support COREV branching immediate.
	*gcc/config/riscv/riscv.md: Include COREV machine description.
	*gcc/config/riscv/riscv.opt: Add COREV_BI target mask.
	*gcc/testsuite/gcc.target/riscv/cv-bi-beqimm-compile.c: Add COREV branching immediate tests for GCC testsuite.
	*gcc/testsuite/gcc.target/riscv/cv-bi-beqimm.c: Likewise.
	*gcc/testsuite/gcc.target/riscv/cv-bi-bneimm-compile.c: Likewise.
	*gcc/testsuite/gcc.target/riscv/cv-bi-bneimm.c: Likewise.

Signed-off-by: Enrico Tabanelli <enrico.tabanelli@embecosm.com>

### CODE REVIEW

**Comment by NandniJamnadas** [comment]
Hi @EnricoTabanelli , would you be able to rebase the updated version of COREV-GCC. This version includes our new Zc* commits? If you want me to do this for you, I would be happy to. I can rebase it onto a new branch so that you can then pull it into xcorevbi_upstream.

**Comment by NBruschi** [comment]
=== gcc Summary ===

# of expected passes            2736
# of expected failures          6
# of unresolved testcases       6
# of unsupported tests          201

**Comment by NBruschi** [comment]
```
                === gcc Summary ===

# of expected passes            2736
# of expected failures          6
# of unresolved testcases       6
# of unsupported tests          201

```

**Comment by NandniJamnadas** [comment]
This work has been picked up by @NandniJamnadas and under this PR [CV32E40Pv2 Immediate Branch Auto-Generation Support](https://github.com/openhwgroup/corev-gcc/pull/38). As this work is under a different PR, we can close this PR.

**Pull request closed without merging**
